### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by maakep** [maakep/CommanderKleek#1]
- [x] Button  -> On click, this.scale.setTo(0.8) onInputDown
- [x] CostButton extends Button(?) or new. if cost > gold, tint red. 
- [ ] Experience & levels & graphical level up bar & show level
- [x] Food farmers
- [x] Gold miners
- [ ] Upgradable stats every level
- [ ] Quests/challenges? Text dialogue pops up with a challenge "Commander! The farmers are getting stressed, their workload needs to be lessened. Hire (Farmers*1.2) more farmers to lessen their burden or else they will all leave!"
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] ... art
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]
